/**
 * lib/category-synonyms.ts
 *
 * Keyword → category/subcategory mapping for ApnaMap's smart
 * business-type detector.  Covers English, Hinglish, and common
 * Hindi script terms used by shop owners in cities like Prayagraj.
 *
 * weight: 1 = generic (word matches many contexts)
 *         2 = specific (strong signal for this category)
 *         3 = definitive (uniquely identifies this business type)
 */

export interface SynonymEntry {
  category: string;    // category slug
  subcategory: string; // subcategory slug
  tags: string[];      // suggested auto-tags for the shop
  weight: 1 | 2 | 3;
}

// Multi-word keys are tried as bigrams before single tokens.
export const SYNONYM_MAP: Record<string, SynonymEntry> = {

  // ── GROCERY & DAILY NEEDS ──────────────────────────────────────────
  "kirana":              { category: "grocery-daily-needs", subcategory: "kirana-store",          tags: ["kirana", "grocery"],             weight: 3 },
  "kiryana":             { category: "grocery-daily-needs", subcategory: "kirana-store",          tags: ["kirana", "grocery"],             weight: 3 },
  "kiranna":             { category: "grocery-daily-needs", subcategory: "kirana-store",          tags: ["kirana", "grocery"],             weight: 3 },
  "ration":              { category: "grocery-daily-needs", subcategory: "kirana-store",          tags: ["ration", "grocery"],             weight: 2 },
  "grocery":             { category: "grocery-daily-needs", subcategory: "general-store",         tags: ["grocery"],                       weight: 2 },
  "general store":       { category: "grocery-daily-needs", subcategory: "general-store",         tags: ["general store"],                 weight: 3 },
  "provision":           { category: "grocery-daily-needs", subcategory: "general-store",         tags: ["provisions", "grocery"],         weight: 2 },
  "supermarket":         { category: "grocery-daily-needs", subcategory: "general-store",         tags: ["supermarket"],                   weight: 2 },
  "sabzi":               { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["vegetables", "sabzi"],           weight: 3 },
  "subzi":               { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["vegetables", "sabzi"],           weight: 3 },
  "vegetable":           { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["vegetables"],                    weight: 2 },
  "vegetables":          { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["vegetables"],                    weight: 2 },
  "fruit":               { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["fruits"],                        weight: 2 },
  "fruits":              { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["fruits"],                        weight: 2 },
  "phal":                { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["fruits", "phal"],                weight: 3 },
  "फल":                  { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["fruits", "फल"],                  weight: 3 },
  "सब्जी":               { category: "grocery-daily-needs", subcategory: "fruits-vegetables",     tags: ["vegetables", "सब्जी"],           weight: 3 },
  "dairy":               { category: "grocery-daily-needs", subcategory: "dairy-milk-booth",      tags: ["dairy", "milk"],                 weight: 3 },
  "milk":                { category: "grocery-daily-needs", subcategory: "dairy-milk-booth",      tags: ["milk", "dairy"],                 weight: 2 },
  "doodh":               { category: "grocery-daily-needs", subcategory: "dairy-milk-booth",      tags: ["milk", "dairy"],                 weight: 3 },
  "dudh":                { category: "grocery-daily-needs", subcategory: "dairy-milk-booth",      tags: ["milk", "dairy"],                 weight: 3 },
  "दूध":                 { category: "grocery-daily-needs", subcategory: "dairy-milk-booth",      tags: ["milk", "dairy"],                 weight: 3 },
  "atta":                { category: "grocery-daily-needs", subcategory: "atta-rice-pulses",      tags: ["atta", "flour"],                 weight: 3 },
  "rice":                { category: "grocery-daily-needs", subcategory: "atta-rice-pulses",      tags: ["rice", "chawal"],                weight: 2 },
  "chawal":              { category: "grocery-daily-needs", subcategory: "atta-rice-pulses",      tags: ["rice", "chawal"],                weight: 3 },
  "pulses":              { category: "grocery-daily-needs", subcategory: "atta-rice-pulses",      tags: ["pulses", "dal"],                 weight: 2 },
  "dal":                 { category: "grocery-daily-needs", subcategory: "atta-rice-pulses",      tags: ["dal", "pulses"],                 weight: 2 },
  "daal":                { category: "grocery-daily-needs", subcategory: "atta-rice-pulses",      tags: ["dal", "pulses"],                 weight: 2 },
  "ro water":            { category: "grocery-daily-needs", subcategory: "water-supplier-ro-can", tags: ["ro water", "water supplier"],    weight: 3 },
  "water supplier":      { category: "grocery-daily-needs", subcategory: "water-supplier-ro-can", tags: ["water supplier"],               weight: 3 },
  "water can":           { category: "grocery-daily-needs", subcategory: "water-supplier-ro-can", tags: ["water can", "water supplier"],   weight: 3 },
  "lpg":                 { category: "grocery-daily-needs", subcategory: "gas-cylinder-lpg",      tags: ["lpg", "gas"],                   weight: 3 },
  "cylinder":            { category: "grocery-daily-needs", subcategory: "gas-cylinder-lpg",      tags: ["lpg", "gas cylinder"],           weight: 3 },
  "gas cylinder":        { category: "grocery-daily-needs", subcategory: "gas-cylinder-lpg",      tags: ["gas cylinder", "lpg"],           weight: 3 },
  "pan shop":            { category: "grocery-daily-needs", subcategory: "pan-shop",              tags: ["pan", "paan"],                  weight: 3 },
  "paan":                { category: "grocery-daily-needs", subcategory: "pan-shop",              tags: ["paan", "pan"],                  weight: 3 },
  "gutka":               { category: "grocery-daily-needs", subcategory: "pan-shop",              tags: ["paan", "gutka"],                weight: 3 },

  // ── FOOD & BEVERAGES ───────────────────────────────────────────────
  "restaurant":          { category: "food-beverages", subcategory: "restaurant",          tags: ["restaurant", "dining"],             weight: 3 },
  "dining":              { category: "food-beverages", subcategory: "restaurant",          tags: ["dining", "restaurant"],             weight: 2 },
  "dhaba":               { category: "food-beverages", subcategory: "dhaba",               tags: ["dhaba", "food"],                    weight: 3 },
  "daba":                { category: "food-beverages", subcategory: "dhaba",               tags: ["dhaba", "food"],                    weight: 3 },
  "food stall":          { category: "food-beverages", subcategory: "street-food-stall",   tags: ["street food", "stall"],             weight: 3 },
  "street food":         { category: "food-beverages", subcategory: "street-food-stall",   tags: ["street food"],                      weight: 3 },
  "stall":               { category: "food-beverages", subcategory: "street-food-stall",   tags: ["stall", "street food"],             weight: 1 },
  "thela":               { category: "food-beverages", subcategory: "street-food-stall",   tags: ["thela", "street food"],             weight: 3 },
  "chai":                { category: "food-beverages", subcategory: "tea-stall-chai-shop", tags: ["chai", "tea"],                      weight: 3 },
  "chay":                { category: "food-beverages", subcategory: "tea-stall-chai-shop", tags: ["chai", "tea"],                      weight: 3 },
  "चाय":                 { category: "food-beverages", subcategory: "tea-stall-chai-shop", tags: ["chai", "tea"],                      weight: 3 },
  "tea":                 { category: "food-beverages", subcategory: "tea-stall-chai-shop", tags: ["tea", "chai"],                      weight: 2 },
  "tea stall":           { category: "food-beverages", subcategory: "tea-stall-chai-shop", tags: ["tea stall", "chai"],                weight: 3 },
  "chai shop":           { category: "food-beverages", subcategory: "tea-stall-chai-shop", tags: ["chai shop"],                        weight: 3 },
  "juice":               { category: "food-beverages", subcategory: "juice-shop",          tags: ["juice", "fresh juice"],             weight: 3 },
  "juices":              { category: "food-beverages", subcategory: "juice-shop",          tags: ["juice"],                            weight: 2 },
  "mithai":              { category: "food-beverages", subcategory: "sweet-shop-mithai",   tags: ["mithai", "sweets"],                 weight: 3 },
  "meetha":              { category: "food-beverages", subcategory: "sweet-shop-mithai",   tags: ["sweets", "mithai"],                 weight: 3 },
  "मिठाई":               { category: "food-beverages", subcategory: "sweet-shop-mithai",   tags: ["mithai", "sweets"],                 weight: 3 },
  "sweet":               { category: "food-beverages", subcategory: "sweet-shop-mithai",   tags: ["sweets", "mithai"],                 weight: 2 },
  "sweets":              { category: "food-beverages", subcategory: "sweet-shop-mithai",   tags: ["sweets", "mithai"],                 weight: 2 },
  "halwai":              { category: "food-beverages", subcategory: "sweet-shop-mithai",   tags: ["halwai", "mithai"],                 weight: 3 },
  "bakery":              { category: "food-beverages", subcategory: "bakery",              tags: ["bakery", "bread", "cake"],          weight: 3 },
  "bread":               { category: "food-beverages", subcategory: "bakery",              tags: ["bread", "bakery"],                  weight: 2 },
  "cake":                { category: "food-beverages", subcategory: "bakery",              tags: ["cake", "bakery"],                   weight: 2 },
  "biscuit":             { category: "food-beverages", subcategory: "bakery",              tags: ["biscuit", "bakery"],                weight: 2 },
  "momo":                { category: "food-beverages", subcategory: "street-food-stall",   tags: ["momos", "street food"],             weight: 3 },
  "momos":               { category: "food-beverages", subcategory: "street-food-stall",   tags: ["momos", "street food"],             weight: 3 },
  "momo corner":         { category: "food-beverages", subcategory: "street-food-stall",   tags: ["momos", "street food"],             weight: 3 },
  "chowmein":            { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["chowmein", "chinese", "noodles"],   weight: 3 },
  "chowmin":             { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["chowmein", "chinese"],              weight: 3 },
  "chaumin":             { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["chowmein", "chinese"],              weight: 3 },
  "chowmein corner":     { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["chowmein", "street food"],          weight: 3 },
  "chinese":             { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["chinese", "chowmein"],              weight: 2 },
  "noodles":             { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["noodles", "chinese"],               weight: 2 },
  "burger":              { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["burger", "fast food"],              weight: 2 },
  "pizza":               { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["pizza", "fast food"],               weight: 2 },
  "fast food":           { category: "food-beverages", subcategory: "fast-food-chinese",   tags: ["fast food"],                        weight: 3 },
  "tiffin":              { category: "food-beverages", subcategory: "tiffin-service",      tags: ["tiffin", "home food"],              weight: 3 },
  "dabba":               { category: "food-beverages", subcategory: "tiffin-service",      tags: ["tiffin", "dabba"],                  weight: 3 },
  "ice cream":           { category: "food-beverages", subcategory: "ice-cream-parlour",   tags: ["ice cream"],                        weight: 3 },
  "icecream":            { category: "food-beverages", subcategory: "ice-cream-parlour",   tags: ["ice cream"],                        weight: 3 },
  "kulfi":               { category: "food-beverages", subcategory: "ice-cream-parlour",   tags: ["kulfi", "ice cream"],               weight: 3 },
  "lassi":               { category: "food-beverages", subcategory: "juice-shop",          tags: ["lassi", "drinks"],                  weight: 3 },
  "shakes":              { category: "food-beverages", subcategory: "juice-shop",          tags: ["shakes", "drinks"],                 weight: 2 },

  // ── MEAT & FRESH MARKET ────────────────────────────────────────────
  "chicken":             { category: "meat-fresh-market", subcategory: "chicken-shop",  tags: ["chicken", "meat"],    weight: 3 },
  "murga":               { category: "meat-fresh-market", subcategory: "chicken-shop",  tags: ["chicken", "murga"],   weight: 3 },
  "broiler":             { category: "meat-fresh-market", subcategory: "chicken-shop",  tags: ["chicken", "broiler"], weight: 3 },
  "mutton":              { category: "meat-fresh-market", subcategory: "mutton-shop",   tags: ["mutton", "meat"],     weight: 3 },
  "gosht":               { category: "meat-fresh-market", subcategory: "mutton-shop",   tags: ["mutton", "gosht"],    weight: 3 },
  "bakra":               { category: "meat-fresh-market", subcategory: "mutton-shop",   tags: ["mutton", "bakra"],    weight: 3 },
  "fish":                { category: "meat-fresh-market", subcategory: "fish-shop",     tags: ["fish", "seafood"],    weight: 3 },
  "machli":              { category: "meat-fresh-market", subcategory: "fish-shop",     tags: ["fish", "machli"],     weight: 3 },
  "maachli":             { category: "meat-fresh-market", subcategory: "fish-shop",     tags: ["fish", "maachli"],    weight: 3 },
  "seafood":             { category: "meat-fresh-market", subcategory: "fish-shop",     tags: ["seafood", "fish"],    weight: 2 },
  "egg":                 { category: "meat-fresh-market", subcategory: "egg-shop",      tags: ["egg", "anda"],        weight: 3 },
  "eggs":                { category: "meat-fresh-market", subcategory: "egg-shop",      tags: ["eggs", "anda"],       weight: 3 },
  "anda":                { category: "meat-fresh-market", subcategory: "egg-shop",      tags: ["egg", "anda"],        weight: 3 },
  "meat":                { category: "meat-fresh-market", subcategory: "meat-supplier", tags: ["meat"],               weight: 2 },

  // ── FASHION & CLOTHING ─────────────────────────────────────────────
  "garments":            { category: "fashion-clothing", subcategory: "garments-store",       tags: ["garments", "clothes"],   weight: 3 },
  "kapde":               { category: "fashion-clothing", subcategory: "garments-store",       tags: ["clothes", "kapde"],      weight: 3 },
  "kapda":               { category: "fashion-clothing", subcategory: "garments-store",       tags: ["clothes", "kapde"],      weight: 3 },
  "कपड़े":               { category: "fashion-clothing", subcategory: "garments-store",       tags: ["clothes", "kapde"],      weight: 3 },
  "clothes":             { category: "fashion-clothing", subcategory: "garments-store",       tags: ["clothes"],               weight: 2 },
  "clothing":            { category: "fashion-clothing", subcategory: "garments-store",       tags: ["clothing"],              weight: 2 },
  "fashion":             { category: "fashion-clothing", subcategory: "garments-store",       tags: ["fashion"],               weight: 1 },
  "ladies":              { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["ladies", "women"],       weight: 2 },
  "saree":               { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["saree", "ladies wear"],  weight: 3 },
  "sari":                { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["saree", "ladies wear"],  weight: 3 },
  "साड़ी":               { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["saree"],                 weight: 3 },
  "lehenga":             { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["lehenga", "ladies wear"],weight: 3 },
  "kurti":               { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["kurti", "ladies wear"],  weight: 3 },
  "salwar":              { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["salwar", "ladies wear"], weight: 3 },
  "dupatta":             { category: "fashion-clothing", subcategory: "ladies-wear",          tags: ["dupatta", "ladies wear"],weight: 3 },
  "mens":                { category: "fashion-clothing", subcategory: "mens-wear",            tags: ["mens wear", "gents"],    weight: 2 },
  "gents":               { category: "fashion-clothing", subcategory: "mens-wear",            tags: ["gents", "mens wear"],    weight: 2 },
  "kids":                { category: "fashion-clothing", subcategory: "kids-wear",            tags: ["kids", "children"],      weight: 2 },
  "children":            { category: "fashion-clothing", subcategory: "kids-wear",            tags: ["children", "kids"],      weight: 2 },
  "tailor":              { category: "fashion-clothing", subcategory: "tailor",               tags: ["tailor", "stitching"],   weight: 3 },
  "darji":               { category: "fashion-clothing", subcategory: "tailor",               tags: ["tailor", "darji"],       weight: 3 },
  "stitching":           { category: "fashion-clothing", subcategory: "tailor",               tags: ["stitching", "tailor"],   weight: 2 },
  "boutique":            { category: "fashion-clothing", subcategory: "boutique",             tags: ["boutique"],              weight: 3 },
  "shoe":                { category: "fashion-clothing", subcategory: "shoe-shop",            tags: ["shoes", "footwear"],     weight: 3 },
  "shoes":               { category: "fashion-clothing", subcategory: "shoe-shop",            tags: ["shoes", "footwear"],     weight: 3 },
  "footwear":            { category: "fashion-clothing", subcategory: "shoe-shop",            tags: ["footwear", "shoes"],     weight: 2 },
  "chappal":             { category: "fashion-clothing", subcategory: "shoe-shop",            tags: ["chappal", "footwear"],   weight: 3 },
  "sandal":              { category: "fashion-clothing", subcategory: "shoe-shop",            tags: ["sandals", "footwear"],   weight: 2 },
  "bag":                 { category: "fashion-clothing", subcategory: "bag-shop",             tags: ["bags"],                  weight: 2 },
  "bags":                { category: "fashion-clothing", subcategory: "bag-shop",             tags: ["bags"],                  weight: 2 },
  "jewellery":           { category: "fashion-clothing", subcategory: "jewellery-artificial", tags: ["jewellery"],             weight: 3 },
  "jewelry":             { category: "fashion-clothing", subcategory: "jewellery-artificial", tags: ["jewellery"],             weight: 3 },
  "artificial jewellery":{ category: "fashion-clothing", subcategory: "jewellery-artificial", tags: ["artificial jewellery"],  weight: 3 },
  "imitation jewellery": { category: "fashion-clothing", subcategory: "jewellery-artificial", tags: ["imitation jewellery"],   weight: 3 },
  "bangle":              { category: "fashion-clothing", subcategory: "bangle-shop",          tags: ["bangles", "chudi"],      weight: 3 },
  "bangles":             { category: "fashion-clothing", subcategory: "bangle-shop",          tags: ["bangles", "chudi"],      weight: 3 },
  "chudi":               { category: "fashion-clothing", subcategory: "bangle-shop",          tags: ["bangles", "chudi"],      weight: 3 },
  "churiyan":            { category: "fashion-clothing", subcategory: "bangle-shop",          tags: ["bangles", "churiyan"],   weight: 3 },

  // ── BEAUTY & PERSONAL CARE ─────────────────────────────────────────
  "salon":               { category: "beauty-personal-care", subcategory: "salon",          tags: ["salon", "haircut"],         weight: 3 },
  "saloon":              { category: "beauty-personal-care", subcategory: "salon",          tags: ["salon", "haircut"],         weight: 3 },
  "barber":              { category: "beauty-personal-care", subcategory: "salon",          tags: ["barber", "salon"],          weight: 3 },
  "nai":                 { category: "beauty-personal-care", subcategory: "salon",          tags: ["barber", "nai"],            weight: 3 },
  "haircut":             { category: "beauty-personal-care", subcategory: "salon",          tags: ["haircut", "salon"],         weight: 3 },
  "hair":                { category: "beauty-personal-care", subcategory: "salon",          tags: ["hair", "salon"],            weight: 2 },
  "parlour":             { category: "beauty-personal-care", subcategory: "beauty-parlour", tags: ["parlour", "beauty"],        weight: 3 },
  "parlor":              { category: "beauty-personal-care", subcategory: "beauty-parlour", tags: ["parlour", "beauty"],        weight: 3 },
  "beauty parlour":      { category: "beauty-personal-care", subcategory: "beauty-parlour", tags: ["beauty parlour"],           weight: 3 },
  "beauty":              { category: "beauty-personal-care", subcategory: "beauty-parlour", tags: ["beauty"],                   weight: 2 },
  "spa":                 { category: "beauty-personal-care", subcategory: "spa",            tags: ["spa", "massage"],           weight: 3 },
  "massage":             { category: "beauty-personal-care", subcategory: "spa",            tags: ["massage", "spa"],           weight: 2 },
  "cosmetic":            { category: "beauty-personal-care", subcategory: "cosmetic-shop",  tags: ["cosmetics", "beauty"],      weight: 3 },
  "cosmetics":           { category: "beauty-personal-care", subcategory: "cosmetic-shop",  tags: ["cosmetics", "beauty"],      weight: 3 },
  "makeup":              { category: "beauty-personal-care", subcategory: "cosmetic-shop",  tags: ["makeup", "cosmetics"],      weight: 2 },
  "mehndi":              { category: "beauty-personal-care", subcategory: "beauty-parlour", tags: ["mehndi", "beauty"],         weight: 3 },
  "tattoo":              { category: "beauty-personal-care", subcategory: "tattoo-studio",  tags: ["tattoo"],                   weight: 3 },

  // ── HEALTH & MEDICAL ───────────────────────────────────────────────
  "medical":             { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["medical", "pharmacy"],     weight: 3 },
  "medical store":       { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["medical store"],           weight: 3 },
  "pharmacy":            { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["pharmacy", "medicine"],    weight: 3 },
  "chemist":             { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["chemist", "pharmacy"],     weight: 3 },
  "medicine":            { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["medicine", "pharmacy"],    weight: 3 },
  "dawai":               { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["medicine", "dawai"],       weight: 3 },
  "dawa":                { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["medicine", "dawa"],        weight: 3 },
  "दवाई":                { category: "health-medical", subcategory: "pharmacy-medical-store", tags: ["medicine", "दवाई"],        weight: 3 },
  "clinic":              { category: "health-medical", subcategory: "clinic",                 tags: ["clinic", "doctor"],        weight: 3 },
  "doctor":              { category: "health-medical", subcategory: "clinic",                 tags: ["doctor", "clinic"],        weight: 2 },
  "hospital":            { category: "health-medical", subcategory: "hospital",               tags: ["hospital"],                weight: 3 },
  "nursing home":        { category: "health-medical", subcategory: "hospital",               tags: ["nursing home", "hospital"],weight: 3 },
  "diagnostic":          { category: "health-medical", subcategory: "diagnostic-center",      tags: ["diagnostic", "tests"],     weight: 3 },
  "pathology":           { category: "health-medical", subcategory: "pathology-lab",          tags: ["pathology", "lab"],        weight: 3 },
  "lab":                 { category: "health-medical", subcategory: "pathology-lab",          tags: ["lab", "tests"],            weight: 2 },
  "optical":             { category: "health-medical", subcategory: "optical-shop",           tags: ["optical", "glasses"],      weight: 3 },
  "glasses":             { category: "health-medical", subcategory: "optical-shop",           tags: ["glasses", "optical"],      weight: 2 },
  "spectacles":          { category: "health-medical", subcategory: "optical-shop",           tags: ["spectacles", "glasses"],   weight: 3 },
  "chashma":             { category: "health-medical", subcategory: "optical-shop",           tags: ["glasses", "chashma"],      weight: 3 },
  "lens":                { category: "health-medical", subcategory: "optical-shop",           tags: ["lens", "optical"],         weight: 2 },
  "dental":              { category: "health-medical", subcategory: "dental-clinic",          tags: ["dental", "teeth"],         weight: 3 },
  "dentist":             { category: "health-medical", subcategory: "dental-clinic",          tags: ["dentist", "dental"],       weight: 3 },
  "physio":              { category: "health-medical", subcategory: "physiotherapy",          tags: ["physiotherapy"],           weight: 3 },
  "physiotherapy":       { category: "health-medical", subcategory: "physiotherapy",          tags: ["physiotherapy"],           weight: 3 },

  // ── HOME & FURNITURE ───────────────────────────────────────────────
  "furniture":           { category: "home-furniture", subcategory: "furniture-shop",      tags: ["furniture"],                  weight: 3 },
  "sofa":                { category: "home-furniture", subcategory: "furniture-shop",      tags: ["sofa", "furniture"],          weight: 2 },
  "almirah":             { category: "home-furniture", subcategory: "furniture-shop",      tags: ["almirah", "furniture"],       weight: 3 },
  "home decor":          { category: "home-furniture", subcategory: "home-decor",          tags: ["home decor"],                 weight: 3 },
  "decor":               { category: "home-furniture", subcategory: "home-decor",          tags: ["decor", "home"],              weight: 2 },
  "mattress":            { category: "home-furniture", subcategory: "mattress-store",      tags: ["mattress", "gadda"],          weight: 3 },
  "gadda":               { category: "home-furniture", subcategory: "mattress-store",      tags: ["mattress", "gadda"],          weight: 3 },
  "razai":               { category: "home-furniture", subcategory: "mattress-store",      tags: ["razai", "bedding"],           weight: 3 },
  "pillow":              { category: "home-furniture", subcategory: "mattress-store",      tags: ["pillow", "bedding"],          weight: 2 },
  "curtain":             { category: "home-furniture", subcategory: "curtains-furnishing", tags: ["curtains", "furnishing"],     weight: 3 },
  "curtains":            { category: "home-furniture", subcategory: "curtains-furnishing", tags: ["curtains", "furnishing"],     weight: 3 },
  "parda":               { category: "home-furniture", subcategory: "curtains-furnishing", tags: ["curtains", "parda"],          weight: 3 },
  "utensils":            { category: "home-furniture", subcategory: "kitchen-utensils",    tags: ["utensils", "bartan"],         weight: 3 },
  "bartan":              { category: "home-furniture", subcategory: "kitchen-utensils",    tags: ["utensils", "bartan"],         weight: 3 },
  "crockery":            { category: "home-furniture", subcategory: "kitchen-utensils",    tags: ["crockery", "utensils"],       weight: 3 },

  // ── HARDWARE & CONSTRUCTION ────────────────────────────────────────
  "hardware":            { category: "hardware-construction", subcategory: "hardware-store",       tags: ["hardware"],                   weight: 3 },
  "cement":              { category: "hardware-construction", subcategory: "cement-sand-bricks",   tags: ["cement", "construction"],     weight: 3 },
  "sand":                { category: "hardware-construction", subcategory: "cement-sand-bricks",   tags: ["sand", "construction"],       weight: 2 },
  "bricks":              { category: "hardware-construction", subcategory: "cement-sand-bricks",   tags: ["bricks", "construction"],     weight: 3 },
  "brick":               { category: "hardware-construction", subcategory: "cement-sand-bricks",   tags: ["bricks", "construction"],     weight: 3 },
  "eent":                { category: "hardware-construction", subcategory: "cement-sand-bricks",   tags: ["bricks", "eent"],             weight: 3 },
  "building materials":  { category: "hardware-construction", subcategory: "building-materials",   tags: ["building materials"],         weight: 3 },
  "tiles":               { category: "hardware-construction", subcategory: "tiles-marble-granite", tags: ["tiles", "flooring"],          weight: 3 },
  "marble":              { category: "hardware-construction", subcategory: "tiles-marble-granite", tags: ["marble", "flooring"],         weight: 3 },
  "granite":             { category: "hardware-construction", subcategory: "tiles-marble-granite", tags: ["granite", "flooring"],        weight: 3 },
  "flooring":            { category: "hardware-construction", subcategory: "tiles-marble-granite", tags: ["flooring", "tiles"],          weight: 2 },
  "paint":               { category: "hardware-construction", subcategory: "paint-shop",           tags: ["paint"],                      weight: 3 },
  "colour":              { category: "hardware-construction", subcategory: "paint-shop",           tags: ["paint", "colour"],            weight: 2 },
  "color":               { category: "hardware-construction", subcategory: "paint-shop",           tags: ["paint", "color"],             weight: 2 },
  "rang":                { category: "hardware-construction", subcategory: "paint-shop",           tags: ["paint", "rang"],              weight: 3 },
  "electrical":          { category: "hardware-construction", subcategory: "electrical-fittings",  tags: ["electrical", "wiring"],       weight: 3 },
  "electric fitting":    { category: "hardware-construction", subcategory: "electrical-fittings",  tags: ["electrical fittings"],        weight: 3 },
  "wiring":              { category: "hardware-construction", subcategory: "electrical-fittings",  tags: ["wiring", "electrical"],       weight: 2 },
  "switch":              { category: "hardware-construction", subcategory: "electrical-fittings",  tags: ["switch", "electrical"],       weight: 2 },
  "plumbing":            { category: "hardware-construction", subcategory: "plumbing-materials",   tags: ["plumbing", "pipe"],           weight: 3 },
  "pipe":                { category: "hardware-construction", subcategory: "plumbing-materials",   tags: ["pipe", "plumbing"],           weight: 2 },
  "sanitary":            { category: "hardware-construction", subcategory: "plumbing-materials",   tags: ["sanitary", "plumbing"],       weight: 3 },

  // ── ELECTRONICS & MOBILE ──────────────────────────────────────────
  "mobile shop":         { category: "electronics-mobile", subcategory: "mobile-shop",           tags: ["mobile", "phone"],            weight: 3 },
  "mobile repair":       { category: "electronics-mobile", subcategory: "mobile-repair",         tags: ["mobile repair"],              weight: 3 },
  "phone repair":        { category: "electronics-mobile", subcategory: "mobile-repair",         tags: ["phone repair"],               weight: 3 },
  "screen repair":       { category: "electronics-mobile", subcategory: "mobile-repair",         tags: ["screen repair", "mobile"],    weight: 3 },
  "mobile":              { category: "electronics-mobile", subcategory: "mobile-shop",           tags: ["mobile", "phone"],            weight: 2 },
  "phone":               { category: "electronics-mobile", subcategory: "mobile-shop",           tags: ["mobile", "phone"],            weight: 2 },
  "laptop":              { category: "electronics-mobile", subcategory: "laptop-computer-shop",  tags: ["laptop", "computer"],         weight: 3 },
  "computer":            { category: "electronics-mobile", subcategory: "laptop-computer-shop",  tags: ["computer", "laptop"],         weight: 3 },
  "electronics":         { category: "electronics-mobile", subcategory: "electronics-store",     tags: ["electronics"],                weight: 2 },
  "appliance":           { category: "electronics-mobile", subcategory: "appliance-store",       tags: ["appliances"],                 weight: 2 },
  "appliances":          { category: "electronics-mobile", subcategory: "appliance-store",       tags: ["appliances"],                 weight: 2 },
  "fridge":              { category: "electronics-mobile", subcategory: "appliance-store",       tags: ["fridge", "appliances"],       weight: 2 },
  "washing machine":     { category: "electronics-mobile", subcategory: "appliance-store",       tags: ["washing machine", "appliance"],weight: 3 },
  "ac":                  { category: "electronics-mobile", subcategory: "appliance-store",       tags: ["ac", "air conditioner"],      weight: 2 },
  "tv":                  { category: "electronics-mobile", subcategory: "appliance-store",       tags: ["tv", "television"],           weight: 2 },
  "cctv":                { category: "electronics-mobile", subcategory: "cctv-security-systems", tags: ["cctv", "security camera"],    weight: 3 },
  "security camera":     { category: "electronics-mobile", subcategory: "cctv-security-systems", tags: ["security camera", "cctv"],    weight: 3 },
  "accessories":         { category: "electronics-mobile", subcategory: "mobile-shop",           tags: ["accessories", "mobile"],      weight: 1 },
  "charger":             { category: "electronics-mobile", subcategory: "mobile-shop",           tags: ["charger", "accessories"],     weight: 2 },

  // ── AUTO & VEHICLES ────────────────────────────────────────────────
  "bike showroom":       { category: "auto-vehicles", subcategory: "bike-showroom",  tags: ["bike showroom"],              weight: 3 },
  "car showroom":        { category: "auto-vehicles", subcategory: "car-showroom",   tags: ["car showroom"],               weight: 3 },
  "used car":            { category: "auto-vehicles", subcategory: "used-vehicles",  tags: ["used car", "second hand"],    weight: 3 },
  "second hand":         { category: "auto-vehicles", subcategory: "used-vehicles",  tags: ["second hand", "used"],        weight: 2 },
  "garage":              { category: "auto-vehicles", subcategory: "garage-repair",  tags: ["garage", "repair"],           weight: 3 },
  "workshop":            { category: "auto-vehicles", subcategory: "garage-repair",  tags: ["workshop", "garage"],         weight: 2 },
  "car wash":            { category: "auto-vehicles", subcategory: "car-wash",       tags: ["car wash"],                   weight: 3 },
  "bike service":        { category: "auto-vehicles", subcategory: "bike-service",   tags: ["bike service"],               weight: 3 },
  "petrol pump":         { category: "auto-vehicles", subcategory: "petrol-pump",    tags: ["petrol pump"],                weight: 3 },
  "petrol":              { category: "auto-vehicles", subcategory: "petrol-pump",    tags: ["petrol pump", "fuel"],        weight: 3 },
  "fuel":                { category: "auto-vehicles", subcategory: "petrol-pump",    tags: ["fuel", "petrol"],             weight: 2 },
  "spare parts":         { category: "auto-vehicles", subcategory: "spare-parts",    tags: ["spare parts"],                weight: 3 },
  "auto parts":          { category: "auto-vehicles", subcategory: "spare-parts",    tags: ["auto parts", "spare parts"],  weight: 3 },
  "tyre":                { category: "auto-vehicles", subcategory: "spare-parts",    tags: ["tyre", "spare parts"],        weight: 3 },
  "tyres":               { category: "auto-vehicles", subcategory: "spare-parts",    tags: ["tyres", "spare parts"],       weight: 3 },
  "bike":                { category: "auto-vehicles", subcategory: "bike-showroom",  tags: ["bike", "motorcycle"],         weight: 2 },
  "car":                 { category: "auto-vehicles", subcategory: "car-showroom",   tags: ["car", "vehicle"],             weight: 2 },
  "vehicle":             { category: "auto-vehicles", subcategory: "car-showroom",   tags: ["vehicle"],                    weight: 1 },

  // ── EDUCATION & STATIONERY ─────────────────────────────────────────
  "school":              { category: "education-stationery", subcategory: "school",          tags: ["school", "education"],  weight: 3 },
  "coaching":            { category: "education-stationery", subcategory: "coaching-center", tags: ["coaching", "classes"],  weight: 3 },
  "coaching center":     { category: "education-stationery", subcategory: "coaching-center", tags: ["coaching center"],      weight: 3 },
  "tuition":             { category: "education-stationery", subcategory: "tuition-classes", tags: ["tuition", "classes"],   weight: 3 },
  "classes":             { category: "education-stationery", subcategory: "tuition-classes", tags: ["classes", "tuition"],   weight: 2 },
  "academy":             { category: "education-stationery", subcategory: "coaching-center", tags: ["academy", "coaching"],  weight: 2 },
  "institute":           { category: "education-stationery", subcategory: "coaching-center", tags: ["institute"],            weight: 2 },
  "stationery":          { category: "education-stationery", subcategory: "stationery-shop", tags: ["stationery", "pens"],   weight: 3 },
  "stationary":          { category: "education-stationery", subcategory: "stationery-shop", tags: ["stationery"],           weight: 3 },
  "book store":          { category: "education-stationery", subcategory: "book-store",      tags: ["book store"],           weight: 3 },
  "books":               { category: "education-stationery", subcategory: "book-store",      tags: ["books"],                weight: 2 },
  "book":                { category: "education-stationery", subcategory: "book-store",      tags: ["books"],                weight: 2 },
  "library":             { category: "education-stationery", subcategory: "library",         tags: ["library"],              weight: 3 },
  "copies":              { category: "education-stationery", subcategory: "stationery-shop", tags: ["copies", "stationery"], weight: 2 },

  // ── SERVICES & UTILITIES ───────────────────────────────────────────
  "photocopy":           { category: "services-utilities", subcategory: "photocopy-print-shop", tags: ["photocopy", "xerox"],   weight: 3 },
  "xerox":               { category: "services-utilities", subcategory: "photocopy-print-shop", tags: ["xerox", "photocopy"],   weight: 3 },
  "printing":            { category: "services-utilities", subcategory: "photocopy-print-shop", tags: ["printing", "photocopy"],weight: 2 },
  "cyber cafe":          { category: "services-utilities", subcategory: "cyber-cafe",           tags: ["cyber cafe"],           weight: 3 },
  "internet cafe":       { category: "services-utilities", subcategory: "cyber-cafe",           tags: ["internet cafe"],        weight: 3 },
  "cyber":               { category: "services-utilities", subcategory: "cyber-cafe",           tags: ["cyber cafe"],           weight: 2 },
  "courier":             { category: "services-utilities", subcategory: "courier-service",      tags: ["courier", "delivery"],  weight: 3 },
  "recharge":            { category: "services-utilities", subcategory: "recharge-shop",        tags: ["recharge", "mobile"],   weight: 3 },
  "recharge shop":       { category: "services-utilities", subcategory: "recharge-shop",        tags: ["recharge shop"],        weight: 3 },
  "internet provider":   { category: "services-utilities", subcategory: "internet-provider",    tags: ["internet provider"],    weight: 3 },
  "broadband":           { category: "services-utilities", subcategory: "internet-provider",    tags: ["broadband", "internet"],weight: 3 },
  "travel agency":       { category: "services-utilities", subcategory: "travel-agency",        tags: ["travel agency"],        weight: 3 },
  "travel":              { category: "services-utilities", subcategory: "travel-agency",        tags: ["travel", "tour"],       weight: 2 },
  "ticket booking":      { category: "services-utilities", subcategory: "ticket-booking",       tags: ["ticket booking"],       weight: 3 },
  "ticket":              { category: "services-utilities", subcategory: "ticket-booking",       tags: ["ticket", "booking"],    weight: 2 },
  "tours":               { category: "services-utilities", subcategory: "travel-agency",        tags: ["tours", "travel"],      weight: 2 },

  // ── PROFESSIONAL & LOCAL SERVICES ─────────────────────────────────
  "electrician":         { category: "professional-local-services", subcategory: "electrician",      tags: ["electrician"],         weight: 3 },
  "bijli":               { category: "professional-local-services", subcategory: "electrician",      tags: ["electrician", "bijli"],weight: 3 },
  "plumber":             { category: "professional-local-services", subcategory: "plumber",          tags: ["plumber"],             weight: 3 },
  "nalkaar":             { category: "professional-local-services", subcategory: "plumber",          tags: ["plumber", "nalkaar"],  weight: 3 },
  "carpenter":           { category: "professional-local-services", subcategory: "carpenter",        tags: ["carpenter"],           weight: 3 },
  "badhai":              { category: "professional-local-services", subcategory: "carpenter",        tags: ["carpenter", "badhai"], weight: 3 },
  "painter":             { category: "professional-local-services", subcategory: "painter",          tags: ["painter", "painting"], weight: 3 },
  "mason":               { category: "professional-local-services", subcategory: "mason",            tags: ["mason"],               weight: 3 },
  "mistri":              { category: "professional-local-services", subcategory: "mason",            tags: ["mistri", "mason"],     weight: 3 },
  "raj mistri":          { category: "professional-local-services", subcategory: "mason",            tags: ["raj mistri", "mason"], weight: 3 },
  "ac repair":           { category: "professional-local-services", subcategory: "ac-repair",        tags: ["ac repair"],           weight: 3 },
  "appliance repair":    { category: "professional-local-services", subcategory: "appliance-repair", tags: ["appliance repair"],    weight: 3 },
  "event planner":       { category: "professional-local-services", subcategory: "event-planner",    tags: ["event planner"],       weight: 3 },
  "event":               { category: "professional-local-services", subcategory: "event-planner",    tags: ["events"],              weight: 2 },
  "catering":            { category: "professional-local-services", subcategory: "event-planner",    tags: ["catering", "events"],  weight: 2 },
  "wedding":             { category: "professional-local-services", subcategory: "event-planner",    tags: ["wedding", "events"],   weight: 2 },
  "shaadi":              { category: "professional-local-services", subcategory: "event-planner",    tags: ["wedding", "shaadi"],   weight: 3 },

  // ── REAL ESTATE & PROPERTY ─────────────────────────────────────────
  "property dealer":     { category: "real-estate-property", subcategory: "property-dealer",    tags: ["property dealer"],          weight: 3 },
  "real estate":         { category: "real-estate-property", subcategory: "property-dealer",    tags: ["real estate", "property"],  weight: 3 },
  "property":            { category: "real-estate-property", subcategory: "property-dealer",    tags: ["property"],                 weight: 3 },
  "zameen":              { category: "real-estate-property", subcategory: "plot-seller",         tags: ["plot", "zameen"],           weight: 3 },
  "plot":                { category: "real-estate-property", subcategory: "plot-seller",         tags: ["plot", "land"],             weight: 3 },
  "land":                { category: "real-estate-property", subcategory: "plot-seller",         tags: ["land", "plot"],             weight: 2 },
  "builder":             { category: "real-estate-property", subcategory: "builder",             tags: ["builder", "construction"],  weight: 3 },
  "rental":              { category: "real-estate-property", subcategory: "rental-services",     tags: ["rental", "rent"],           weight: 3 },
  "rent":                { category: "real-estate-property", subcategory: "rental-services",     tags: ["rent", "rental"],           weight: 2 },
  "flat":                { category: "real-estate-property", subcategory: "rental-services",     tags: ["flat", "rental"],           weight: 2 },
  "apartment":           { category: "real-estate-property", subcategory: "rental-services",     tags: ["apartment", "rental"],      weight: 2 },
  "pg":                  { category: "real-estate-property", subcategory: "pg-hostel",           tags: ["pg", "paying guest"],        weight: 3 },
  "hostel":              { category: "real-estate-property", subcategory: "pg-hostel",           tags: ["hostel", "pg"],              weight: 3 },
  "paying guest":        { category: "real-estate-property", subcategory: "pg-hostel",           tags: ["paying guest", "pg"],        weight: 3 },
  "commercial property": { category: "real-estate-property", subcategory: "commercial-property", tags: ["commercial property"],       weight: 3 },
  "office":              { category: "real-estate-property", subcategory: "commercial-property", tags: ["office", "commercial"],      weight: 2 },

  // ── GIFTS, TOYS & HOBBY ────────────────────────────────────────────
  "gift shop":           { category: "gifts-toys-hobby", subcategory: "gift-shop",        tags: ["gift shop"],           weight: 3 },
  "gifts":               { category: "gifts-toys-hobby", subcategory: "gift-shop",        tags: ["gifts"],               weight: 2 },
  "gift":                { category: "gifts-toys-hobby", subcategory: "gift-shop",        tags: ["gifts"],               weight: 2 },
  "toy shop":            { category: "gifts-toys-hobby", subcategory: "toy-shop",         tags: ["toy shop"],            weight: 3 },
  "toys":                { category: "gifts-toys-hobby", subcategory: "toy-shop",         tags: ["toys"],                weight: 2 },
  "toy":                 { category: "gifts-toys-hobby", subcategory: "toy-shop",         tags: ["toys"],                weight: 2 },
  "sports goods":        { category: "gifts-toys-hobby", subcategory: "sports-goods",     tags: ["sports goods"],        weight: 3 },
  "sports":              { category: "gifts-toys-hobby", subcategory: "sports-goods",     tags: ["sports"],              weight: 2 },
  "cricket":             { category: "gifts-toys-hobby", subcategory: "sports-goods",     tags: ["cricket", "sports"],   weight: 2 },
  "flower shop":         { category: "gifts-toys-hobby", subcategory: "flower-shop",      tags: ["flower shop"],         weight: 3 },
  "flowers":             { category: "gifts-toys-hobby", subcategory: "flower-shop",      tags: ["flowers", "florist"],  weight: 2 },
  "phool":               { category: "gifts-toys-hobby", subcategory: "flower-shop",      tags: ["flowers", "phool"],    weight: 3 },
  "decoration items":    { category: "gifts-toys-hobby", subcategory: "decoration-items", tags: ["decoration items"],    weight: 3 },
  "decoration":          { category: "gifts-toys-hobby", subcategory: "decoration-items", tags: ["decoration"],          weight: 2 },
  "wrapping":            { category: "gifts-toys-hobby", subcategory: "gift-shop",        tags: ["gift wrapping"],       weight: 2 },

  // ── PETS & ANIMALS ─────────────────────────────────────────────────
  "pet shop":            { category: "pets-animals", subcategory: "pet-shop",          tags: ["pet shop"],            weight: 3 },
  "pets":                { category: "pets-animals", subcategory: "pet-shop",          tags: ["pets"],                weight: 2 },
  "pet":                 { category: "pets-animals", subcategory: "pet-shop",          tags: ["pets"],                weight: 2 },
  "dog":                 { category: "pets-animals", subcategory: "pet-shop",          tags: ["dog", "pets"],         weight: 2 },
  "aquarium":            { category: "pets-animals", subcategory: "pet-shop",          tags: ["aquarium", "fish"],    weight: 3 },
  "veterinary":          { category: "pets-animals", subcategory: "veterinary-clinic", tags: ["veterinary", "vet"],   weight: 3 },
  "vet":                 { category: "pets-animals", subcategory: "veterinary-clinic", tags: ["vet", "veterinary"],   weight: 3 },
  "animal feed":         { category: "pets-animals", subcategory: "animal-feed-store", tags: ["animal feed"],         weight: 3 },
  "poultry":             { category: "pets-animals", subcategory: "animal-feed-store", tags: ["poultry feed"],        weight: 2 },
  "dairy farming":       { category: "pets-animals", subcategory: "dairy-farming",     tags: ["dairy farming"],       weight: 3 },

  // ── RELIGIOUS & CULTURAL ───────────────────────────────────────────
  "pooja":               { category: "religious-cultural", subcategory: "pooja-items",    tags: ["pooja", "puja items"],  weight: 3 },
  "puja":                { category: "religious-cultural", subcategory: "pooja-items",    tags: ["puja", "pooja"],        weight: 3 },
  "pooja items":         { category: "religious-cultural", subcategory: "pooja-items",    tags: ["pooja items"],          weight: 3 },
  "agarbatti":           { category: "religious-cultural", subcategory: "pooja-items",    tags: ["agarbatti", "incense"], weight: 3 },
  "dhoop":               { category: "religious-cultural", subcategory: "pooja-items",    tags: ["dhoop", "pooja"],       weight: 3 },
  "diya":                { category: "religious-cultural", subcategory: "pooja-items",    tags: ["diya", "pooja"],        weight: 3 },
  "temple":              { category: "religious-cultural", subcategory: "temple-shop",    tags: ["temple", "mandir"],     weight: 2 },
  "mandir":              { category: "religious-cultural", subcategory: "temple-shop",    tags: ["mandir", "temple"],     weight: 3 },
  "spiritual":           { category: "religious-cultural", subcategory: "spiritual-store",tags: ["spiritual"],            weight: 2 },
  "flower vendor":       { category: "religious-cultural", subcategory: "flower-vendor",  tags: ["flower vendor"],        weight: 3 },
  "prasad":              { category: "religious-cultural", subcategory: "temple-shop",    tags: ["prasad", "temple"],     weight: 3 },
  "rudraksh":            { category: "religious-cultural", subcategory: "spiritual-store",tags: ["rudraksh", "spiritual"],weight: 3 },
};

// Quick examples shown in the onboarding input
export const EXAMPLE_INPUTS = [
  "momos chowmein burger",
  "mobile repair and accessories",
  "plot for sale in jhalwa",
  "kirana and dairy",
  "ladies boutique and saree",
  "chicken mutton fish",
  "pharmacy medical store",
  "hair salon parlour",
  "coaching center tuition",
  "hardware cement tiles",
];
